name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install project and dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          rm -rf core/tokens.json
          printf '{\n"access_token" : "${{ secrets.ACCESS_TOKEN }}",\n"access_token_secret" : "${{ secrets.ACCESS_TOKEN_SECRET }}",\n"api_key" : "${{ secrets.API_KEY }}",\n"api_secret_key" : "${{ secrets.API_SECRET_KEY }}"\n}' > core/tokens.json
          export

      - name: Build static page
        shell: bash
        run: |
          make clean
          make html

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.0'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository:  gp2w/gp2w.github.io
          publish_branch: master
          publish_dir: ./127.0.0.1:8050
